# Álgebra Lineal

In [1]:
%pylab inline
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg
# Biblioteca para algebra lineal

Populating the interactive namespace from numpy and matplotlib


## Álgebra de Matrices

Los arreglos de **numpy** no se comportan como las _matrices_ de sus clases de algebra lineal.

En lugar de ello, hacen _broadcasting_, como hemos visto en las clases pasadas. Recordemos que _broadcasting_ es mapear las operaciones a cada uno de los elementos del arreglo (_array_).

¿Pero que pasa si queremos hacer operaciones matriciales? Bueno, **numpy** nos ofrece las siguientes opciones.

Definamos el arreglo $\textbf{A}$

In [2]:
A = array([[n+m*10 for n in range(1,5)] for m in range(1,5)])

In [3]:
A

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

El arreglo $\textbf{A}$, es eso, un arreglo (_array_), es el mismo objeto que hemos visto con anterioridad. **Numpy** soporta (en beneficio de los usuarios de `matlab`/`GNU Octave`) el objeto `matrix`. Sin embargo: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html

Tomaron la decisión de migrar todo lo necesario a sólo `np.array()`

<div class="alert alert-warning">
    
Como probablemente en un futuro se topen con cosas de `matlab / GNU Octave` les recomiendo esta [liga](http://wiki.scipy.org/NumPy_for_Matlab_Users)
</div>

Nada nuevo en cuanto las dimensiones de $\textbf{A}$:

In [4]:
print(A.shape)

(4, 4)


Pero recordemos que cuando hacemos slicing nos regresa arreglos unidimensionales, no vectores... :/

In [5]:
A

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [6]:
y = A[:,0]
print(y)
print(y.shape)

[11 21 31 41]
(4,)


Sin embargo podemos modificar ligeramente el código para que nos regrese un array vertical unidimensional: 

In [7]:
y = A[:,:1]
print(y)
print(y.shape)

[[11]
 [21]
 [31]
 [41]]
(4, 1)


Podemos hacer todo tipo de operaciones con los arrays, y a partir de python 3.5, podemos usar el operador `@`, para multiplicar. 

In [8]:
A

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [9]:
np.dot(A,y)

array([[1350],
       [2390],
       [3430],
       [4470]])

In [10]:
A@y

array([[1350],
       [2390],
       [3430],
       [4470]])

Ahora intentémoslo al revés: 

In [12]:
y@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 1)

<div class="alert alert-info">
    
**Ejercicio** ¿Por qué no funcionó?
</div>

In [14]:
y

array([[11],
       [21],
       [31],
       [41]])

In [15]:
y.T

array([[11, 21, 31, 41]])

In [16]:
A.T

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44]])

In [24]:
y.T@A@y

array([[354640]])

In [17]:
A@A

array([[1350, 1400, 1450, 1500],
       [2390, 2480, 2570, 2660],
       [3430, 3560, 3690, 3820],
       [4470, 4640, 4810, 4980]])

In [18]:
n=2
np.linalg.matrix_power(A,n) # A^n

array([[1350, 1400, 1450, 1500],
       [2390, 2480, 2570, 2660],
       [3430, 3560, 3690, 3820],
       [4470, 4640, 4810, 4980]])

In [20]:
Id = np.identity(4)
Id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Soluciones de sistemas de ecuaciones

Los sistemas de ecuaciones lineales se pueden plantear como un problema matricial, del tipo $\textbf{A}\textbf{x} = \textbf{B}$, por ejemplo:

$3x + 6y -5z = 12$

$x - 3y + 2z = -2$

$5x -y + 4z = 10$

La solución de las ecuaciones matriciales $\textbf{A}\textbf{x} = \textbf{b}$, es $\textbf{x} = \textbf{A}^{-1}\textbf{b}$ (Si la matriz $\textbf{A}$ es invertible, claro está)

In [21]:
A = np.array([[3,6,-5],
              [1,-3,2],
              [5,-1,4]])
A

array([[ 3,  6, -5],
       [ 1, -3,  2],
       [ 5, -1,  4]])

In [22]:
b = np.array([[12],
               [-2],
               [10]])
b

array([[12],
       [-2],
       [10]])

In [23]:
x = np.linalg.matrix_power(A,-1)@b
print(x)

[[1.75]
 [1.75]
 [0.75]]


In [24]:
A@x

array([[12.],
       [-2.],
       [10.]])

<div class="alert alert-danger">
    Es importante tener en mente que las matrices generalmente no son invertibles, por lo que este método de solución, no siempre funciona. 
</div>

<div class="alert alert-danger">
El invertir matrices es un proceso largo y pesado que además puede ser demasiado cálculo para lo que se requiere. 
</div>

Lo mejor cuando estamos resolviendo sistemas de ecuaciones y en general casi siempre que se "requiere" una inversa es resolver el sistema de ecuaciones lineales: 

In [26]:
x = linalg.solve(A,b)
x

array([[1.75],
       [1.75],
       [0.75]])

In [37]:
A@x

array([[12.],
       [-2.],
       [10.]])

## Transformaciones

In [38]:
C = np.array([[1j, 2j], [3j, 4j]])
C

array([[0.+1.j, 0.+2.j],
       [0.+3.j, 0.+4.j]])

El conjugado de una matriz compleja $\textbf{C}$

In [39]:
conjugate(C)

array([[0.-1.j, 0.-2.j],
       [0.-3.j, 0.-4.j]])

El hermitiano de una matriz ( es decir, conjugado y transpuesta)

In [40]:
conjugate(C).T

array([[0.-1.j, 0.-3.j],
       [0.-2.j, 0.-4.j]])

El hermitiano de una matríz real (Como $\textbf{A}$) es simplemente la transpuesta

In [41]:
conjugate(A).T

array([[ 3,  1,  5],
       [ 6, -3, -1],
       [-5,  2,  4]])

La parte $\Re$ e $\Im$ de una matriz se pueden extraer:

In [42]:
real(C)

array([[0., 0.],
       [0., 0.]])

In [43]:
imag(C)

array([[1., 2.],
       [3., 4.]])

La inversa de una matriz, (**si existe**):

In [53]:
C

array([[0.+1.j, 0.+2.j],
       [0.+3.j, 0.+4.j]])

In [54]:
inv(C)

array([[0.+2.j , 0.-1.j ],
       [0.-1.5j, 0.+0.5j]])

In [46]:
np.linalg.matrix_power(C,-1)

array([[0.+2.j , 0.-1.j ],
       [0.-1.5j, 0.+0.5j]])

In [47]:
inv(C)@C

array([[1.00000000e+00+0.j, 0.00000000e+00+0.j],
       [1.11022302e-16+0.j, 1.00000000e+00+0.j]])

## Determinantes 

In [48]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [49]:
linalg.det(A)

-2.0

In [52]:
B = np.arange(1,10).reshape(3,3)
det(B)

0.0

In [51]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<div class="alert alert-info">
Sean las matrices $\textbf{A}$ y $\textbf{B}$ definidas abajo, compruebe las propiedades $1-6$ de los determinantes como se muestran en la página de la [Wikipedia](http://en.wikipedia.org/wiki/Determinant)
</div>

In [16]:
A = np.array([[-2,2,-3],
               [-1,1,3],
               [2,0,-1]])
print(A)

[[-2  2 -3]
 [-1  1  3]
 [ 2  0 -1]]


In [4]:
#1
linalg.det(A)==linalg.det(A.T)

True

In [8]:
math.isclose(linalg.det(A),linalg.det(A.T))

True

In [17]:
B = np.array([[5, -3, 2],
               [1,0,2],
               [2,-1,3]])
print(B)

[[ 5 -3  2]
 [ 1  0  2]
 [ 2 -1  3]]


In [18]:
#2
A@B

array([[-14,   9,  -9],
       [  2,   0,   9],
       [  8,  -5,   1]])

In [19]:
linalg.det(A@B)

89.99999999999987

In [20]:
linalg.det(A)*linalg.det(B)

90.0

In [21]:
math.isclose(linalg.det(A@B),linalg.det(A)*linalg.det(B) )

True

In [22]:
#3 determinante de la inversa de una matriz es igual al inverso del determinante de la matriz
math.isclose(linalg.det(inv(A)), 1/linalg.det(A))


True

In [ ]:
#4 

<div class="alert alert-info">
    
**Ejercicio**: Resuelva el sistema de ecuaciones lineales mostrado anteriormente, pero usando la [**Regla de Cramer**](http://en.wikipedia.org/wiki/Cramer's_rule)
</div>

El módulo `scipy.linalg` permite la creación de matrices especiales, tales como matrices diagonales de bloques `block_diag`, matrices circulantes `circulant`, matrices _companion_ (`companion`), matrices de Hadamard (`hadamard`), Hankel (`hankel`), Hilbert (`hilbert`), Hilbert invertida (`invhilbert`), Leslie (`leslie`), Toeplitz (`toeplitz`) y matrices triangulares (`tri`, `tril`, `triu`).

In [25]:
A = np.array([[3,6,-5],
              [1,-3,2],
              [5,-1,4]])
A

array([[ 3,  6, -5],
       [ 1, -3,  2],
       [ 5, -1,  4]])

In [26]:
b = np.array([[12],
               [-2],
               [10]])
b

array([[12],
       [-2],
       [10]])

In [27]:
A.shape

(3, 3)

In [28]:
x=np.empty([3,1])
x

array([[1.],
       [1.],
       [1.]])

In [30]:
for i in range(A.shape[1]):
    Ai=np.copy(A)
    Ai[:,[i]]=b
    x[i]=linalg.det(Ai)/linalg.det(A)
    print(x)

[[1.75]
 [1.  ]
 [1.  ]]
[[1.75]
 [1.75]
 [1.  ]]
[[1.75]
 [1.75]
 [0.75]]


In [31]:
A@x-b

array([[-1.77635684e-15],
       [ 8.88178420e-16],
       [ 0.00000000e+00]])

In [ ]:
linalg.circulant([1,2,3])

### Eigenvalores y eigenvectores

El cálculo de _eigenvectores_ y _eigenvalores_ es uno de los más complicados (y útiles) a realizarse en matrices cuadradas. **SciPy** posee varias rutinas para calcularlas:

- `eigvals`

- `eigvalsh`

- `eigvals_banded`

Y los respectivos métodos para _eigenvectores_: `eig`, `eigh` y `eigh_banded`.

<div class="alert alert-info">
    
**Ejercicio:** Calcule los _eigenvectores_ e _eigenvalores_ de las siguientes matrices usando los diferentes métodos.

- $$ A =  \left[\begin{matrix} 4 & 6 & 4\\-2 & -3 & -4\\0 & 0 & 2\end{matrix}\right] $$

- $$ B = \left[\begin{matrix} 1 & 2 & 0\\0 & 1 & 2\\0 & 0 & 1\end{matrix}\right] $$

**NOTA** Si es posible, utilice los métodos de creación de matrices especiales.

</div>

## Normas matriciales.

Scipy también nos puede calcular diferentes normas matriciales y vectoriales: 

In [27]:
np.linalg.norm([1,1,1,1])

2.0

In [28]:
np.linalg.norm([1,1,1,1], np.inf)

1.0

In [ ]:
A

In [ ]:
np.linalg.norm(A, 'fro')

In [ ]:
np.linalg.norm(A, -np.inf)

## Algebra Lineal Simbólica

Es posible manipular algebraicamente a matrices de expresiones simbólicas, usando la clase de `Matrix` de **SimPy** . 

In [2]:
from ipywidgets import interact
from IPython.display import display

<div class="alert alert-danger">
    
Cuando se trabaja con **Sympy** **no** se puede usar  `%pylab inline` ya que `%pylab%` importa variables que entraran en conflicto con **Sympy**. Es mejor usar, `%matplotlib inline` e importar `numpy` y `matplotlib`.
</div>

In [29]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [30]:
from sympy import *

In [31]:
init_printing(use_latex='mathjax')

In [41]:
x = Symbol('x')
y = Symbol('y')
A = Matrix([[1,x], [y,1]])
A

⎡1  x⎤
⎢    ⎥
⎣y  1⎦

In [36]:
A[0,0]

1

In [34]:
A[:,1]

⎡x⎤
⎢ ⎥
⎣1⎦

In [39]:
A**2

⎡x⋅y + 1    2⋅x  ⎤
⎢                ⎥
⎣  2⋅y    x⋅y + 1⎦

In [42]:
A.inv()

⎡   1        -x    ⎤
⎢────────  ────────⎥
⎢-x⋅y + 1  -x⋅y + 1⎥
⎢                  ⎥
⎢  -y         1    ⎥
⎢────────  ────────⎥
⎣-x⋅y + 1  -x⋅y + 1⎦

In [43]:
I = A.inv()*A
I

⎡    x⋅y         1                           ⎤
⎢- ──────── + ────────            0          ⎥
⎢  -x⋅y + 1   -x⋅y + 1                       ⎥
⎢                                            ⎥
⎢                           x⋅y         1    ⎥
⎢          0            - ──────── + ────────⎥
⎣                         -x⋅y + 1   -x⋅y + 1⎦

In [44]:
I = simplify(I)
I

⎡1  0⎤
⎢    ⎥
⎣0  1⎦

Para matrices pequeñas, puedes calcular los _eigenvalores_ simbólicamente.

In [45]:
A.eigenvals()

⎧      _____       _____       ⎫
⎨1 - ╲╱ x⋅y : 1, ╲╱ x⋅y  + 1: 1⎬
⎩                              ⎭

In [47]:
A.subs({x:0, y:1})

⎡1  0⎤
⎢    ⎥
⎣1  1⎦

<div class="alert alert-info">
    
**Ejercicio**: Cree matrices de $3\times3$ de *Hilbert*, *Leslie* y *Circulantes* y muéstrelas de manera simbólica.
</div>