# Introducción

**NumPy** es la *librería* de python para computación científica. **NumPy** agrega al lenguaje lo siguiente: Arreglos multidimensionales, operaciones elemento por elemento (técnica conocida como *broadcasting*), algebra lineal, manipulación de imágenes, la habilidad de utilizar código `C/C++` y `FORTRAN`, entre muchas otras.

La mayor parte de los componentes del sistema de computo científico de Python, están construidas encima de **NumPy**, un ejemplo que veremos en el curso es `SciPy`.

Para poder utilizar **NumPy**, es necesario importarlo a la sesión del `notebook`.

### Bibliografía de soporte

- *NumPy Beginner's Guide* _Ivan Idris_,  PACKT Publishing, 2015
- *NumPy Cookbook* _Ivan Idris_, PACKT Publishing, 2012
- *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython*, _Wes McKinney_, O'REILLY, 2012
- [Learn (official Numpy list of tutorials](https://numpy.org/learn/)

In [4]:
import numpy as np

## Arrays

El principal componente de **NumPy** es el `array`, el cual es una versión más poderosa, pero menos flexible que las listas de python.

In [2]:
lst =  [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
lst[2:3]

[3]

In [6]:
arr[2:3]

array([3])

<div class="alert alert-info">
    
**Ejercicio:** Repite los ejercicios de listas del *Lecture 2* con `array`.
</div>

In [7]:
lst[-1] = "Las listas pueden tener varios tipos de datos"
lst

[1, 2, 3, 4, 'Las listas pueden tener varios tipos de datos']

In [8]:
arr[-1] = "Los arreglos no..."

ValueError: invalid literal for int() with base 10: 'Los arreglos no...'

Una vez inicializado el `array` sólo puede contener un tipo de dato.

In [9]:
arr.dtype

dtype('int64')

In [10]:
arr[-1] = 1.23456
arr

array([1, 2, 3, 4, 1])

In [11]:
arr.dtype

dtype('int64')

Sacrificamos la versatilidad de las listas por velocidad. Creeemos un `array` de 1 millón de elementos y multiplicaremos cada uno de ellos por una constante (*broadcasting*).

In [12]:
arr = np.arange(1e7)

In [13]:
lst = arr.tolist()

Las listas no soportan *broadcasting* por lo que crearemos una función que lo simule

In [17]:
def lst_multiplicacion( alist , scalar ): 
    for i , val in enumerate ( alist ): 
        alist [ i ] = val
    return alist

In [14]:
%timeit arr * 1.1

28 ms ± 2.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
%timeit lst_multiplicacion(lst, 1.1)

744 ms ± 7.24 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Creación de arrays

In [25]:
arr = np.array([1,2,3,4,5])

In [26]:
arr

array([1, 2, 3, 4, 5])

In [20]:
arr = np.arange(10,21)

In [21]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
arr = np.zeros(5)

In [28]:
arr

array([0., 0., 0., 0., 0.])

In [29]:
arr = np.linspace(0,1,100)
#you give it a start and an end and it fills everything else

In [30]:
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [31]:
arr = np.logspace(0,1,100, base=10)

In [32]:
arr

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

In [33]:
arr2d = np.zeros((5,5))

In [34]:
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
cubo = np.zeros((5,5,5)).astype(int)+1

In [36]:
cubo

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [37]:
cubo = np.ones((5,5,5)).astype(np.float16)

In [38]:
cubo

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [40]:
cubo.dtype

dtype('float16')

In [39]:
np.empty((2,3,4)) #just arbitrary values

array([[[4.68729193e-310, 0.00000000e+000, 6.92478590e-310,
         6.92478589e-310],
        [6.92478590e-310, 6.92478590e-310, 6.92478590e-310,
         6.92478590e-310],
        [6.92478590e-310, 6.92478590e-310, 6.92478590e-310,
         6.92478590e-310]],

       [[6.92478590e-310, 6.92478590e-310, 6.92478590e-310,
         6.92478590e-310],
        [6.92478590e-310, 6.92478590e-310, 6.92478590e-310,
         6.92478590e-310],
        [6.92478590e-310, 6.92478590e-310, 6.92478590e-310,
         6.92478590e-310]]])

<div class="alert alert-danger">
    
**PELIGRO**

¡`np.empty` no devuelve un arreglo de ceros!
</div>

In [41]:
np.eye(4) #matriz identidad de 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.random.rand(3)

array([0.9602013 , 0.39450707, 0.02820106])

In [44]:
np.random.rand(4)

array([0.28945371, 0.3761064 , 0.4149434 , 0.86973748])

## Reshaping

In [62]:
arr = np.arange(1000)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [64]:
arr3d = arr.reshape((10,10,10))

In [65]:
arr3d.ndim

3

In [66]:
arr3d.shape

(10, 10, 10)

In [67]:
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [68]:
arr3d = arr.reshape((100,10))
arr3d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [54]:
arr = np.arange(200)

In [55]:
arr2d = arr.reshape((10,20))

In [56]:
arr2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

## Aplanar

In [74]:
arr = np.zeros((4,4,4,4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

      

In [58]:
arr.shape

(4, 4, 4, 4)

In [76]:
arr_plano = arr.ravel()
arr_plano

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [60]:
arr_plano.shape

(256,)

## *Broadcasting*

In [69]:
data = np.array([1,2,3,4,5])

In [70]:
data

array([1, 2, 3, 4, 5])

In [71]:
data + 1

array([2, 3, 4, 5, 6])

In [72]:
data * 2

array([ 2,  4,  6,  8, 10])

In [73]:
data ** 2

array([ 1,  4,  9, 16, 25])

## Transponer

In [80]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [82]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [83]:
arr.T #transpose

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

¿Qué pasa en varias dimensiones?

In [85]:
arr  = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [86]:
arr  = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr

In [ ]:
arr.transpose((1,0,2))

`transpose` recibe una `tupla` de los índices de los ejes y los permuta. `(O_o)`

<div class="alert alert-info">
    
**Ejercicio** Diseña un ejemplo multidimensional, donde sea obvia la permutación
</div>

## Slicing e Indexado

En el ejercicio vimos que el indexado en `arrays` de 1D es igual que el indexado y *slicing* de las listas de python. ¿Pero que sucede en $n-$dimensiones?

### Cuidado al hacer *slicing*

In [87]:
arr = np.arange(10)

In [88]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

El _slincing_ genera (devuelve) una **vista**, si modificas el =array= original, la **vista** se ve modificada también.

In [89]:
arr_slice =  arr[5:8]

In [90]:
arr_slice

array([5, 6, 7])

In [91]:
arr_slice[1]= 12345678

In [92]:
arr_slice

array([       5, 12345678,        7])

In [93]:
arr #está modificando el original, no es un nuevo arreglo

array([       0,        1,        2,        3,        4,        5,
       12345678,        7,        8,        9])

In [98]:
arr_slice[:] = 345

In [99]:
arr_slice

array([345, 345, 345])

In [100]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [101]:
arr2 = np.copy(arr)

In [102]:
arr2

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [103]:
arr2[5:8] = [5,6,7]

In [104]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [106]:
np.may_share_memory(arr, arr_slice)

True

In [107]:
np.may_share_memory(arr, arr2)

False

### Multidimensional

In [108]:
arr = np.arange(9)

In [109]:
arr.shape = (3,3)

In [110]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [111]:
arr.ndim

2

In [112]:
arr[2]

array([6, 7, 8])

In [113]:
arr[-1]

array([6, 7, 8])

In [114]:
arr[1][1]

4

In [115]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [116]:
arr[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [117]:
arr[:1,:2]

array([[0, 1]])

In [118]:
arr[1:,:2]

array([[3, 4],
       [6, 7]])

In [120]:
arr[1,]

array([3, 4, 5])

In [121]:
arr[1,:2]

array([3, 4])

In [122]:
arr[1,2:]

array([5])

In [123]:
arr[:,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [124]:
arr[:,:1]

array([[0],
       [3],
       [6]])

<div class="alert alert-info">
    
**Ejercicio**:

Explique como funciona el *slicing* $n$-dimensional.
</div>

In [125]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
index = arr > 2

In [127]:
index

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [135]:
arr[index] #regresa los valores que cumplen con eso de index

array([3, 4, 5, 6, 7, 8])

In [132]:
arr2 = arr[index]

In [133]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [134]:
arr2

array([3, 4, 5, 6, 7, 8])

<div class="alert alert-info">
    
**Ejercicio:**
(a) Cree un arreglo de 2D $5\times5$ lleno de unos. (b) Utilice *slicing* para seleccionar 1 cuadrado alrededor del centro  y llénelo con $2$s.  (c) Utilice *slicing* para seleccionar  el centro y asígnele $4$. (d) Copie el arreglo. (e) Utilice *slicing* lógico para seleccionar el cuadro interno y asígnele cero. (f) En el cuadro copiado, al centro y al cuadro exterior asígnele $0$.
</div>

## Fancy Indexing

In [138]:
arr = np.ones((5,4))

In [139]:
for i in range(5):
    arr[i] = i

In [140]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [141]:
arr[[4,3,1,2]] #está ordenando las filas en el orden que le des

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [142]:
arr[[-3,-2,-1]]

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

¿Puedes explicar que hace el _fancy indexing_?

## Funciones Universales

Las *funciones universales*  realizan operaciones elemento por elemento en los arreglos. 

In [177]:
arr = np.arange(10)

In [178]:
arr = -1*arr

In [179]:
arr

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [180]:
arr = np.abs(arr)

In [181]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [183]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [184]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [185]:
np.logical_not(arr)

array([ True, False, False, False, False, False, False, False, False,
       False])

In [186]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
arr = np.random.randn(10)

In [188]:
arr

array([ 0.53990705, -0.89473533, -0.80880369,  0.22458245, -0.25738173,
       -0.58812419, -0.01531458, -0.99575681, -1.07233292, -0.26701498])

In [189]:
np.ceil(arr)

array([ 1., -0., -0.,  1., -0., -0., -0., -0., -1., -0.])

In [190]:
np.floor(arr)

array([ 0., -1., -1.,  0., -1., -1., -1., -1., -2., -1.])

In [191]:
np.rint(arr) #Round elements of the array to the nearest integer

array([ 1., -1., -1.,  0., -0., -1., -0., -1., -1., -0.])

In [29]:
arr2 = np.ones(10)

In [161]:
np.add(arr, arr2)

array([ 0.99094083, -1.26966978,  1.47004514,  0.43798826,  0.84050289,
        0.77719458,  1.44919791,  0.49648796,  1.59609171,  2.35382446])

In [162]:
np.multiply(arr, arr2)

array([-0.00905917, -2.26966978,  0.47004514, -0.56201174, -0.15949711,
       -0.22280542,  0.44919791, -0.50351204,  0.59609171,  1.35382446])

In [163]:
np.maximum(arr, arr2)

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.35382446])

In [164]:
np.logical_and(arr, arr2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## Agregaciones

Funciones que calculan operaciones a lo largo de un eje.

In [192]:
arr

array([ 0.53990705, -0.89473533, -0.80880369,  0.22458245, -0.25738173,
       -0.58812419, -0.01531458, -0.99575681, -1.07233292, -0.26701498])

In [193]:
arr.sum()

-4.134974746893441

In [194]:
arr.mean()

-0.4134974746893441

In [5]:
arr = np.random.randn(5,4)

In [6]:
arr

array([[-1.33609289,  0.91516472, -0.42564358, -0.29612768],
       [-2.30428378, -2.54067552, -1.40734281,  0.63574462],
       [ 0.93728565,  0.74994105, -0.19435828,  1.10657068],
       [-0.08686591,  0.86408335, -1.39696507, -0.66524461],
       [ 0.77978878,  0.33107078,  0.67311211,  1.13085608]])

In [10]:
arr.sum()

-2.5299822934277545

In [198]:
arr.mean()

0.29229006951722963

In [13]:
arr.sum(1) #is 0 if adding columns, is 1 if adding rows

array([-1.14269942, -5.61655749,  2.59943911, -1.28499224,  2.91482775])

In [16]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [17]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [20]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [21]:
(arr > 5).sum() #this adds the true values

4

In [23]:
(arr[arr > 5]).sum() #this adds the values larger than 5

30

## Operaciones de conjuntos

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.unique(arr2)

array([1.])

In [32]:
np.intersect1d(arr, arr2)

array([1.])

<div class="alert alert-info">
    
**Ejercicio** Usando la definición de [**cuadrados mágicos**](http://en.wikipedia.org/wiki/Magic_square) crea una función que reciba un arreglo e indique si es o no un cuadrado mágico.
</div>

## Casting

In [33]:
a = np.array([1,2,3])
a

array([1, 2, 3])

El tipo de mayor jerarquía define el _cast_

In [34]:
a + 1.5

array([2.5, 3.5, 4.5])

La asignación **no** cambia el tipo del arreglo.

In [35]:
a.dtype

dtype('int64')

In [36]:
(a + 1.5).dtype

dtype('float64')

## Tipos 

In [40]:
np.iinfo(np.int8)   # Prueba con 8, 16, 32 y 64 bits

iinfo(min=-128, max=127, dtype=int8)

<div class="alert alert-info">
    
**Ejercicio** ¿Qué pasa con `int`?
</div>

In [43]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [44]:
np.finfo(np.float64).eps

2.220446049250313e-16

In [45]:
np.float32(1e-8) + np.float32(1) == 1

True

In [46]:
np.float64(1e-8) + np.float64(1) == 1

False

In [ ]:
np.float64(1e-17) + np.float64(1) == 1
#something about the value of epsilon being below and it turning into zero

## Estructura de datos

In [47]:
muestra = np.zeros((6,), dtype=[('codigo', 'S4'),('posicion', float), ('valor', float)])

In [48]:
muestra

array([(b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.),
       (b'', 0., 0.), (b'', 0., 0.)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [49]:
muestra.ndim

1

In [50]:
muestra.shape

(6,)

In [51]:
muestra.dtype.names

('codigo', 'posicion', 'valor')

In [52]:
muestra[:] = [('ALFA',   1, 0.37), ('BETA', 1, 0.11), ('TAU', 1,   0.13),('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]

In [53]:
muestra

array([(b'ALFA', 1. , 0.37), (b'BETA', 1. , 0.11), (b'TAU', 1. , 0.13),
       (b'ALFA', 1.5, 0.37), (b'ALFA', 3. , 0.11), (b'TAU', 1.2, 0.13)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [54]:
muestra.shape

(6,)

In [55]:
muestra['codigo']

array([b'ALFA', b'BETA', b'TAU', b'ALFA', b'ALFA', b'TAU'], dtype='|S4')

In [ ]:
muestra[0]['valor']

In [ ]:
muestra[['codigo', 'valor']]

In [ ]:
muestra[muestra['codigo'] == 'ALFA']

## Broadcasting (Segunda vuelta)

<div class="alert alert-warning">
    
**NOTA** Las imágenes y ejemplos están basados en la presentación  **The NumPy Array: A Structure for
Efficient Numerical Computation** de _Stéfan van der Walt_ de 2010.
</div>

### 1D

<img src="images/broadcasting_1d.png"/>

In [ ]:
x = np.arange(4)
x

In [ ]:
x + 3

### 2D

<img src="images/broadcasting_2d.png"/>

In [ ]:
a = np.arange(12).reshape((3,4))
print( a.shape)
a

In [ ]:
b = np.array([1,2,3])
print( b.shape)
b

In [ ]:
a+b

<div class="alert alert-danger">
    
**Observa muy bien lo que acaba de pasar, el error es a propósito...**
</div>

In [ ]:
b = b[:, np.newaxis]
print (b.shape)
b

In [ ]:
a + b