<div class="alert alert-info">
Sean las matrices $\textbf{A}$ y $\textbf{B}$ definidas abajo, compruebe las propiedades $1-6$ de los determinantes como se muestran en la página de la [Wikipedia](http://en.wikipedia.org/wiki/Determinant)
</div>

### El determinante de una matriz y el de su traspuesta coinciden


In [3]:
%pylab inline
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg

Populating the interactive namespace from numpy and matplotlib


In [4]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [5]:
A.T

array([[1, 3],
       [2, 4]])

In [6]:
linalg.det(A)

-2.0

In [7]:
linalg.det(A.T)

-2.0

In [10]:
(linalg.det(A)) == (linalg.det(A.T))

True

In [20]:
#Usar la función near
math.isclose(linalg.det(A),linalg.det(A.T))

True

#### Una propiedad fundamental del determinante es su comportamiento multiplicativo frente al producto de matrices:

In [21]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [22]:
B = np.array([[5,6],[7,8]])
B

array([[5, 6],
       [7, 8]])

In [26]:
A@B

array([[19, 22],
       [43, 50]])

In [27]:
linalg.det(A@B)

3.9999999999999574

In [28]:
linalg.det(A)*linalg.det(B)

4.000000000000007

In [29]:
math.isclose(linalg.det(A@B),linalg.det(A)*linalg.det(B))

True

#### 4. El determinante de la inversa de una matriz es igual al inverso del determinante de la matriz. 

In [30]:
math.isclose(linalg.det(inv(A)),1/linalg.det(A))

True

#### 6. La matriz de los adjuntos de una matriz A dada de dimensión n tiene un determinante igual al determinante de A elevado a n-1.

### Resolver sistema regla de cramer

Los sistemas de ecuaciones lineales se pueden plantear como un problema matricial, del tipo $\textbf{A}\textbf{x} = \textbf{b}$, por ejemplo:

$3x + 6y -5z = 12$

$x - 3y + 2z = -2$

$5x -y + 4z = 10$

In [32]:
A = np.array([[3,6,-5],
              [1,-3,2],
              [5,-1,4]])
A

array([[ 3,  6, -5],
       [ 1, -3,  2],
       [ 5, -1,  4]])

In [33]:
b = np.array([[12],
               [-2],
               [10]])
b

array([[12],
       [-2],
       [10]])

In [53]:
x=np.empty([3,1])
for i in range(A.shape[1]):
    Ai=np.copy(A)
    Ai[:,[i]]=b
    x[i]= linalg.det(Ai) / linalg.det(A)
    #print(x)
    print(Ai)

[[12  6 -5]
 [-2 -3  2]
 [10 -1  4]]
[[ 3 12 -5]
 [ 1 -2  2]
 [ 5 10  4]]
[[ 3  6 12]
 [ 1 -3 -2]
 [ 5 -1 10]]


In [46]:
A@x-b

array([[ 1.5 ],
       [-2.25],
       [-6.75]])

In [52]:
print(A)

[[ 3  6 -5]
 [ 1 -3  2]
 [ 5 -1  4]]


In [ ]:
CALMEN A RUBEN 